import Head from "next/head";
import Image from "next/image";

export default function Home() {
  let selected = 0;
  return (
    <>
      <Head>
        <title>Interactive Rating Component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className="h-full  px-5 bg-[#121417] ">
        <div
          id="question"
          className=" h-full  flex items-center place-content-center"
        >
          <div className="gradient h-[45%] xl:max-w-[365px] xl:h-[400px] rounded-3xl text-white flex flex-col justify-evenly px-6">
            <div className="relative w-[40px] h-[40px] z-0 bg-gray-500/10 rounded-full">
              <Image
                className="z-10 absolute transform translate-x-[12px] translate-y-[12px]  "
                src="/icon-star.svg"
                width={17}
                height={16}
                alt="star"
              ></Image>
              <div className=""></div>
            </div>

            <p className="text-2xl font-bold">How did we do?</p>
            <p className="text-[.98rem] opacity-70 ">
              Please let us know how we did with your support request. All
              feedback is appreciated to help us improve our offering!
            </p>
            <div className="flex w-full justify-between px-1 ">
              {[1, 2, 3, 4, 5].map((num) => (
                <button
                  key={num}
                  className="bg-[#7C8798]/10  w-[40px] h-[40px] rounded-full flex pt-1 justify-center items-center hover:bg-[#fb7413] hover:font-bold focus:bg-[#959EAC] focus:font-bold"
                  onClick={function SelectRating() {
                    selected = num;
                  }}
                >
                  <p className="opacity-60">{num}</p>
                </button>
              ))}
            </div>

            <button
              className="bg-[#FB7413] rounded-full p-2 flex justify-center content-start hover:bg-[#FFFFFF] hover:text-[#FB7413] font-bold tracking-wide xl:mt-3"
              onClick={function Submit() {
                if (selected !== 0) {
                  const text = document.getElementById("score");

                  if (text)
                    text.textContent = `You selected ${selected} out of 5`;

                  const question = document.getElementById("question");
                  question?.classList.add("hidden");
                  const answer = document.getElementById("answer");
                  answer?.classList.remove("hidden");
                  selected = 0;
                }
              }}
            >
              SUBMIT
            </button>
          </div>
        </div>
        <div
          id="answer"
          className=" h-full  flex items-center place-content-center hidden"
        >
          <div
            className="h-full  w-full absolute"
            onClick={() => {
              const answer = document.getElementById("answer");
              answer?.classList.add("hidden");
              const question = document.getElementById("question");
              question?.classList.remove("hidden");
            }}
          ></div>
          <div className="gradient xl:max-w-[365px] xl:h-[400px] h-[55%]  rounded-3xl text-white flex flex-col justify-evenly items-center p-6 ">
            <Image
              src="/illustration-thank-you.svg"
              alt="thanks!"
              width={162}
              height={108}
            ></Image>

            <p
              id="score"
              className="text-[#FB7413] bg-[#7C8798]/20 py-1 px-2 rounded-full"
            ></p>
            <p className="font-bold text-2xl">Thank you!</p>
            <p className="text-center text-white/80 ">
              We appreciate you taking the time to give a rating. If you ever
              need more support, don’t hesitate to get in touch!
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
